### ISSUE TITLE
Edit Team - Team details (name, location) are not loaded when editing an existing team

### ISSUE THREAD

**Issue by smaraf** [johnneed/GreenUpVermont#11]
* Go to My Teams
* Create a new team if one doesn't exist already (note that when clicking save on the new team the user experience would be much nicer if the team summaries screen would be loaded once the new team has been saved or some other UI indication that the team has saved successfully
* Go back to Team Summaries Screen and load the newly created team

Expected Result: Team details would be loaded 
Actual Result: All team details fields load with default values (empty)

**Comment by smara093** [comment]
I'm also going to fix the scroll on the My Teams screen

**Comment by smaraf** [comment]
PR: https://github.com/johnneed/GreenUpVermont/pull/41

**Comment by smaraf** [comment]
PR merged, closing
