### ISSUE TITLE
New Public Team Form issues

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#125]
**Date field** - Formatting of date after selection is SatMay052018
**Start Time field** - tip says Select a Date (but it does pop up Time)
**End Time Field** - tip says Select a Date (but it does pop up Time)
**Notes field** - is only one long line of text, why isn't it wrapping? And centered paragraphs are generally harder to read

You need white space between the Save and Cancel buttons. I'd also recommend making them look more button-like.

- Katrina Meyers

**Comment by kmeyersvt** [comment]
This was on an Android.

**Comment by jmargolisvt** [comment]
**Date field** - Formatting of date after selection is SatMay052018  -- What's wrong with this format (assuming you just lost the spaces in the paste) @kmeyersvt ?  What do you think it should be?

These items have already been fixed.  The deployed app must not have included the latest stuff.
**Start Time field** - tip says Select a Date (but it does pop up Time) 
**End Time Field** - tip says Select a Date (but it does pop up Time)

**Comment by kmeyersvt** [comment]
I didn't lose the spaces in the paste, that is exactly how it looks. That is the problem. @jmargolisvt 

I would recommend Month DD, YYYY for clarity.

**Comment by jmargolisvt** [comment]
**Update:** The changes I made to correct the verbiage were in the wrong place because we had duplicate code, as were the spacing issues.  Thanks for the screen shot @kmeyersvt.  💯

**Comment by kmeyersvt** [comment]
@jmargolisvt  I'm not seeing any changes in the current version is Expo. Being new to the team, I'm not sure how new builds are deployed for testing?

**Comment by jmargolisvt** [comment]
My changes were just merged in this morning @kmeyersvt .  @johnneed is in charge of deploys, so he could tell you when there's a new deploy available for testing.

**Comment by kmeyersvt** [comment]
@jmargolisvt  Everything passes here except the Save and Cancel buttons still need to be separated by white space. Do you want a new issue for that since this one is closed?

**Comment by jmargolisvt** [comment]
I'll make an issue for it.  This will allow me to clean up the duplicate code some more.
