### ISSUE TITLE
Town picker on iOS is difficult to use

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#126]
Not sure the best way to resolve this but it would be nice if could behave like the he date picker, with a pop-up modal that expands the control.

**Comment by kmeyersvt** [comment]
Is there a way to have it pop to a town that you enter in, or snap while typing? Scrolling through a long list in Android is tedious if you live in a town on the bottom of the list.

**Comment by jmargolisvt** [comment]
I was thinking of implementing this or something like it: https://www.npmjs.com/package/react-native-autocomplete-input  Any other ideas out there?

**Comment by kmeyersvt** [comment]
That looks good to me, and what I was thinking for functionality.

**Comment by kmeyersvt** [comment]
It isn't working this way - there is no prompt inside the box and no auto-complete. I opened a new issue because this also appears to have affected the Notes text input (or maybe it was something else).
