### ISSUE TITLE
Send a Message screen

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#128]
Why is the text centered in the box? from a readability perspective, left justified is always better.

Cancel needs to be a button, it is displaying as a word below the Send Message button.

I did not receive my message.  I sent one to Team Blue, not sure if you got it or not.

**Comment by johnneed** [comment]
Let's left align all our textInputs.

**Comment by jmargolisvt** [comment]
@kmeyersvt I own Blue Team and I got a request to join.  Did you send another message too?

**Comment by kmeyersvt** [comment]
That was the only join request I sent. I'm glad you got it!

I see that I conflated two issues here. Join requests are separate from just messages, correct? I would have thought I could send a message that my team members would see. I didn't see it in messages.

**Comment by jmargolisvt** [comment]
Closing this story because the UI issues are fixed.  I opened https://github.com/johnneed/GreenUpVermont/issues/142 as a separate bug to look into messages.
