### ISSUE TITLE
Edit Team - TeamEditorMap does not have a "key" property

### ISSUE THREAD

**Issue by smaraf** [johnneed/GreenUpVermont#13]
When loading the team-editor-details screen a warning is displayed saying 

`Warning: Each child in an array or iterator should have a unique "key" prop.
[exp]
[exp] Check the render method of `TeamEditorMap`. See https://fb.me/react-warning-keys for more information.`

This issue doesn't have a functional impact.

**Comment by johnneed** [comment]
Could not reproduce.  I'm guessing some nice person already fixed this.
