### ISSUE TITLE
Map is not showing blue markers

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#130]
I added a route on the map under Team Katrina for Sand Road.
I added Katrina Team 2 and in the map, I tagged Colchester Pond Road (which is adjacent).

I see a line next to Sand Road where I tagged Team Katrina's location, but I don't see blue markers. 
The white markers that are on there while I'm tagging the route are hard to see. The very first pin I placed was the traditional red pin, but after I tapped "Remove Last Marker" to remove one, the icons turned white.

![image](https://user-images.githubusercontent.com/37085086/37003791-42e422c4-209c-11e8-8f01-f564117b5e53.png)

**Comment by smaraf** [comment]
PR was merged to master, and I verified blue markers are now displays where other teams areas are defined. Closing
