### ISSUE TITLE
Did not receive invitation - (Move from GMail to an Email Service) 

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#132]
In my team screen, I invited my other email address to the team and I didn't receive the email. It was not in my Spam folder.

**Comment by johnneed** [comment]
https://sendgrid.com/docs/Integrate/Tutorials/Zapier/sending_when_new_firebase_child_records_added.html

**Comment by johnneed** [comment]
#153 will solve this issue
https://github.com/johnneed/GreenUpVermont/issues/153
