### ISSUE TITLE
Edit Team Screen - UI need to be made intuitive (and maybe even beautiful)

### ISSUE THREAD

**Issue by smaraf** [johnneed/GreenUpVermont#14]
According to the Wireframes, there should be a single field for selecting the team's town. Rename _Clean Up Location_ to _Town_ and remove superfluous _Location_ field.

**Comment by johnneed** [comment]
The first field is so people can search for public teams in their town.  The second field is for specifying where the actual clean up site is like "Burlington High School"  or  "200 Block of Pine Street"

We need to make this distinction clearing in  the UI.  

I'm going to change this ticked to a more general one of fixing the UI.
