### ISSUE TITLE
Who am I sending my message to?

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#148]
The fixes in the message box look great, but, who am I sending my message to? I can see the messages I send in my message box, but when I'm writing a new message, if I'm on more than one team, there's no place to pick which team. I'm on Team Blue and Katrina Test 1.

**Comment by johnneed** [comment]
If there's only one team or the team was selected on the My Teams screen the picker is not shown.
However we should should see the team displayed as text in that case

**Comment by kmeyersvt** [comment]
Given that the Messages page is the first one that displays when you launch the app, you wouldn't know which team you had selected most recently. All the messages are in one screen. It's probably scope creep, but shouldn't I be able to choose which team I'm seeing messages for and sending them to in the Messages screen?

**Comment by johnneed** [comment]
All Fixed

**Comment by kmeyersvt** [comment]
This is great,  thanks!
