### ISSUE TITLE
Edit Team - Add/Display areas on the map

### ISSUE THREAD

**Issue by smaraf** [johnneed/GreenUpVermont#15]
The edit team screen currently displays a map with a pin on it but lacks the ability to define and display areas on the map.

**Comment by johnneed** [comment]
I recommend debugging this using a real phone as the <Map> control doesn't work the same using the simulator

**Comment by johnneed** [comment]
This is looking awesome Smara!
Any chance we change the pins to some other icon?  Otherwise they might be confused with trash drops.

**Comment by smaraf** [comment]
Sure thing @johnneed  - I changed it to https://material.io/icons/#ic_person_pin_circle in my last commit. Unsure if this is the best icon to use but it'll be pretty easy to change it if we want to.

**Comment by smaraf** [comment]
[PR](https://github.com/johnneed/GreenUpVermont/pull/75) was merged to master and I verified this now works fine in master. Closing
