### ISSUE TITLE
team message appears on user details

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#157]
Messages like "You own this team" This makes sense on the team details page but not on the team members page.  

We should delete these messages from the screen.

**Comment by kbeaulieu802** [comment]
@johnneed, are you looking to have the text in the red box removed?

![image](https://user-images.githubusercontent.com/6385796/37254422-05fe54e8-2514-11e8-971f-174f8b5db69d.png)

**Comment by johnneed** [comment]
Okay I screwed up this issue.    :-( 

What I really want is the user profile info to appear on the user details screen, which is the screen you go to when you click that link.

I'm going to to close this ticket.  I must of been drinking or really really tired. when I made this.
