### ISSUE TITLE
Town info on trash tracker doesn’t update when gps moves to new town

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#158]
I opened the app in Fairfax and the drove to Williston.  The town message still said I was still in Fairfax.  We probably need to attach a listener to a gps event

**Comment by smaraf** [comment]
PR: https://github.com/johnneed/GreenUpVermont/pull/175

**Comment by smaraf** [comment]
PR merged to master and verified the fix is in place. Will test this better this afternoon when I go into Burlington.
