### ISSUE TITLE
Cannot save profile

### ISSUE THREAD

**Issue by jmargolisvt** [johnneed/GreenUpVermont#162]
When you try to save your profile (Menu --> My Profile) it errors with: Cannot read property 'toLowerCase' of null

**Comment by kbeaulieu802** [comment]
@jmargolisvt I received this error once when looking into this, i tracked the error down to a null `email` attribute on the `profile` object. In an attempt to get the data coming from the login source, google in my case. I logged out and back in and the issue appears to be fixed. I did apply code changes from master to my dev branch before working on this, not sure if something in those changes fixed this and i just needed to re-authenticate.

**Comment by jmargolisvt** [comment]
Still seeing this error: Cannot read property 'toLowerCase' of null

**Comment by jmargolisvt** [comment]
@kbeaulieu802 You were exactly right.  @johnneed pointed me to it, I followed the same procedure and now all's well. 💯
