### ISSUE TITLE
Messages improvements

### ISSUE THREAD

**Issue by jmargolisvt** [johnneed/GreenUpVermont#164]
1.  Add a "Delete Message" button to the message detail view.
2. Add some way to filter messages by team.
3. Request to Join Team emails should probably be auto-deleted once an action is taken on them.
4. Messages from teams you have left should also be removed.  Currently, they still appear, but the team name is null.

**Comment by johnneed** [comment]
#1 has been added as a separate V2 issue.
#2 has been added as a separate V2 issue.
#3 is done.
#4 has been added as a separate MVP bug .
Closing this ticket
