### ISSUE TITLE
Something happened to the text entry

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#172]
City lookup and Notes now bring you to a one line box when adding a new team. . The Notes box also shows one line even though it's using the whole screen.

This is Android.

**Comment by kmeyersvt** [comment]
![screenshot_2018-03-12-20-16-18](https://user-images.githubusercontent.com/37085086/37316078-75ee0f58-2633-11e8-87a5-a80cfefbce71.png)

**Comment by kmeyersvt** [comment]
![screenshot_2018-03-12-20-15-33](https://user-images.githubusercontent.com/37085086/37316087-80fe42e6-2633-11e8-96bf-498de38700b8.png)

**Comment by johnneed** [comment]
This may be a side-effect of the keyboard hiding view.

**Comment by jmargolisvt** [comment]
@johnneed See this comment: https://github.com/johnneed/GreenUpVermont/commit/e727f298296ca94a4f7565ea3ddf43b4816f98d0

**Comment by jmargolisvt** [comment]
The docs suggest that the offending prop be added on a platform-specific basis, so that's what I did.  Seems ok on my Android device and the ios simulator.  https://facebook.github.io/react-native/docs/keyboardavoidingview.html#behavior
