### ISSUE TITLE
Invitation email is not actionable

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#174]
I received an email inviting me to participate in Green Up Day, but there were no actionable links on the email.  If this is a beginning test, that's fine and you can close this issue, but I wanted to log it.

![image](https://user-images.githubusercontent.com/37085086/37346809-bbab878c-26a6-11e8-999b-b198fcaa3b66.png)

**Comment by johnneed** [comment]
duplicate of 50
