### ISSUE TITLE
Trash drops should show on all trash maps

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#182]
Folks will need to see drops in nearby towns for collections.  We will need the collected trash toggle too

**Comment by smaraf** [comment]
@johnneed What do you mean by all trash maps? Are you maybe thinking all maps - including Team Editor Map and the Team Details Map?

**Comment by smaraf** [comment]
Added toggle for uncollected trash drops and a different pin icon (delete-circle) for displaying them. Uncollected trash drops are now always displayed regardless of whether the town allows roadside drop off or not.

PR: https://github.com/johnneed/GreenUpVermont/pull/187
