### ISSUE TITLE
Trash drop off locations should show on all trash maps.  

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#183]
Let’s use a a different pin for the location to make them distinct.  Color alone isn’t good for color blind folks

**Comment by smaraf** [comment]
Added toggle trash drop off locations and a different pin icon (home-circle) for displaying them. Drop off locations are now always displayed regardless of whether the town allows roadside drop off or not.

One thing that we don't do and perhaps we would want to is to display drop off locations from other towns as well. Currently, we only display the drop off locations in the town you're in but I can imagine a scenario where as a user I would be able to drop trash off at a designated location on my way home, in another city. @johnneed is this something we'd want to do for MVP? It should be fairly easy and I can take a stab at it too.

PR: https://github.com/johnneed/GreenUpVermont/pull/187

**Comment by smaraf** [comment]
PR was merged and I verified the fix appears as expected in master. Closing
