### ISSUE TITLE
Email address invalid

### ISSUE THREAD

**Issue by tgerade** [johnneed/GreenUpVermont#202]
Email address containing a period before the @ sign is not valid.  For example: teresagerade.gss@gmail.com is a valid gmail address but I cannot use it on GreenUp App.  Tested with Android.

**Comment by johnneed** [comment]
I tried "John.@example.com"  That got flagged as an invalid Email address because it is.  (good)
I also tried "john.need@example.com"  That was accepted because it is a good email address. (gooder)
Tested in Android and iPhone

 Closing because there doesn't seem to be a bug here.
