### ISSUE TITLE
Survey screen

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#203]
We need a new feature to survey user satisfaction and solicit feedback.

The screen should have a short survey followed by a text box for comments.

The results of survey should be posted to URL that saves the survey data and user information to Firebase.  A Firebase function will need to be created to make this happen.

The survey should included the following questions 
1) How would you rate the Green Up app overall ?   possible answers are 1 to 3 stars
2) Did This app help you find supplies ? possible answers are yes/no
Micah and Teresa : other questions go here.

**Comment by doub1ejack** [comment]
From everything I've read, the key to getting feedback is keeping things short & concise.  What if we just include these three questions: 1 star rating, 1 checkbox and 1 text field:

1.  _"How was your experience overall?"_  If people are seeking out this "Feedback" page, then this probably be a sampling of mostly dissatisfied people.  That's fine, especially if it prevents them from leaving bad reviews on the app store until we can get to the next version.
1.  _"Share your thoughts."_  Just a simple textarea where people can say whatever they want.
1.  _"May we email you with follow-up questions?"_  Just a yes/no checkbox.

The way that third question is worded, we can do two things.  We can contact them with specific troubleshooting questions which could be helpful.  But more importantly, our "follow-up questions" could be a link to a short questionnaire with more detailed questions like Johns example, "Did This app help you find supplies?"

If we keep the in-app questions short, but seek permission to send more extensive questions to their email, then I think we're more likely to catch people at a keyboard where their feedback might be a little more informative.
