### ISSUE TITLE
Show different colors on trash drop icons depending on ownership and status and type

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#208]
Trash drops should have different colors to show status:
These colors are just examples.  Pick whatever colors make sense.
1)  Dark Green:   The drop is yours and it is NOT collected.
2) Light Green : The drop is NOT yours and is NOT collected.
3) Yellow: The drop has been collected.

We should also show different colors for each type such as
1) Trash drop off locations.
2) Supply pickup locations.
3) Cleanup locations.

**Comment by smaraf** [comment]
I updated the data in firebase with Pickup Location coordinates for the ones where we have addresses so far. I also updated the import script to look up coordinates for the Pickup Locations where we have addresses.

**Comment by smaraf** [comment]
PR was merged to master and I verified things look alright there. Closing...
