### ISSUE TITLE
Declining an Invitation should send you back to the previous screen

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#211]
Steps to reproduce:

1) get invited to a team
2) Click on the invitation.
3) Decline the invitation
4) Notice the screen does not update to "Ask to To Join" and you are not redirected back.
5) Go back and notice that you have been removed from the team.

**Comment by jmargolisvt** [comment]
In step 4, I'm seeing the "Ask to To Join" update after I decline the invitation.  Whether I decline or decline-then-ask-to-join-again, when I go back to my inbox, the message is deleted.  The team I requested to join shows up on the My Teams screen with the little clock icon and when I open it, I can Remove Request.  I think this is the desired behavior we are after, no?

**Comment by jmargolisvt** [comment]
This behavior seems ok for now.
