### ISSUE TITLE
No Messages text on messages screen flashes during load.

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#218]
We need to keep the loading screen up until the messages data comes back.  This should be checked in the loading screen.

**Comment by jmargolisvt** [comment]
I'm not sure what needs fixing here.  I do know that you flash through a lot of stuff when the app loads though.  Splash screen --> Green Thoughts --> Loading... --> My Messages.  Whew!  What's the ideal experience here?  What issues do we need to overcome in terms of loading data and showing a wait screen?

**Comment by jmargolisvt** [comment]
This seems ok for now.
