### ISSUE TITLE
Clicking a green flag in the Team Editor map adds a pin for the current team

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#225]
Steps to reproduce : 

1) Create a new Team, "A"
2)  Navigate to the team map and place a  pin.
3) Create another Team, "B"
4) Navigate to the team map and find the green flag for Team A and click it to read the bubble.
5) Notice that a pin was placed for Team B.

Expected Behavior, pins should only be dropped if not clicking on an icon.

**Comment by smaraf** [comment]
@johnneed I can't reproduce this on Android. If I tap on the green flag I can read the bubble and there's no pin added. I wonder if this is something iOS specific - were you using a device or emulator to test?

**Comment by johnneed** [comment]
This seems to be iOs only

**Comment by johnneed** [comment]
@smaraf I think I found the problem.   I was reading the react-native-maps README  and found this setting.

```stopPropagation | Boolean | false | Sets whether this marker should propagate onPress events. Enabling it will stop the parent MapView's onPress from being called. Note: iOS only. Android does not propagate onPressevents. See #1132 for more information.```

I think we just need to set stopPropagation on all markers to "true"

Here's the link to the full README : https://github.com/react-community/react-native-maps/blob/master/docs/marker.md
