### ISSUE TITLE
Set state-level zoom on Team Detail map

### ISSUE THREAD

**Issue by doub1ejack** [johnneed/GreenUpVermont#227]
At the moment the map is zoomed out to the entire US.  Let's just set the zoom to encompass VT instead.
<img width=250 src="https://user-images.githubusercontent.com/1809882/37915508-b05c3f52-30e7-11e8-8748-09e7d895542e.PNG">

**Comment by johnneed** [comment]
One more for you @smaraf

**Comment by smaraf** [comment]
PR was merged to master and I verified the fix is in place. Closing
