### ISSUE TITLE
Android: New Team - Town Lookup is Case Sensitive

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#237]
If I type colche it doesn't find Colchester. 
If I type COLCHE it doesn't find Colchester.
But, if I type Colche, it finds it.

**Comment by kmeyersvt** [comment]
The Town Info page is not case sensitive in its search, FYI.

**Comment by jmargolisvt** [comment]
Fixed in https://github.com/johnneed/GreenUpVermont/pull/244/commits/4a21469b53afa9d33a5b08174b4f3ceaea8d9a27
