### ISSUE TITLE
Android: Cannot add notes in About Me page

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#242]
I have no way to get into the About Me box in My Profile.  The keyboard hides it and when I hit back on my phone to hide the keyboard (which is how Androids work) I cannot tap in the About Me box and it is truncated.

I tried tapping in the About Me box first, so that the keyboard would show up and found that there IS a cursor in there, but it's a few lines down in the box.

![screenshot_2018-03-27-21-14-12](https://user-images.githubusercontent.com/37085086/38063394-f2833c6a-32c6-11e8-9650-6f9ef228a0ce.png)

**Comment by jmargolisvt** [comment]
Can't recreate this one either.  Still a bug?

**Comment by kmeyersvt** [comment]
This is working now too in the new app. Closing.
