### ISSUE TITLE
Login Screen Needs Styling

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#27]

**Comment by jmargolisvt** [comment]
FB and Google both have branding guidelines for login buttons.

https://developers.facebook.com/docs/facebook-login/web/login-button
https://developers.google.com/identity/branding-guidelines

**Comment by johnneed** [comment]
Thanks Jeff, we should probably add the button branding to this issue.

**Comment by jmargolisvt** [comment]
Agreed.  I'm planning on it. ;)

**Comment by jmargolisvt** [comment]
Wasn't able to get the graphics to be responsive.  That's apparently a fair amount of work in React Native and not something it's just set up to do.  So I just restyled them a bit.  Now they both kind of look like the Google official button.  Seems ok for now.
