### ISSUE TITLE
Add Gravatar to profile

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#68]
If no gravatar is available then we should use the user's initials. (per convention)

**Comment by johnneed** [comment]
If the user signs in with Google or Facebook, the profile already has a photoURL attribute.
Otherwise we can try for a Gravatar using the user's email.
If that fails let's fall back to using initials from profile.displayName.

**Comment by kmeyersvt** [comment]
I started seeing my Google Avatar last night for the first time on my Android!
