### ISSUE TITLE
Needs dates on the start on end times for Green Team info

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#82]
Not everyone does Green Up Day on Green Up Day.  We should add a date picker to start and end for Team info.   Of course it should default to May 5th 2018.

**Comment by jmargolisvt** [comment]
Is there a minimum/maximum date that I should set?

**Comment by johnneed** [comment]
I know lots of work places do Green Up on the  Friday before. I'm also guessing some organizations might do stuff on Sunday too.      Either way a two week span should allow folks who are still collecting roadside bags plenty of time to use the app.
