### ISSUE TITLE
Trash Tracker trash drop defaults to San Fran not current GPS location. 

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#9]
This was tested in an emulator not a real phone.  Please check a real phone first that has GPS.

**Comment by smara093** [comment]
This seemed to have worked correctly on my phone; I was able to drop a trash pin of 10 bags of tires in Winooski :)

**Comment by johnneed** [comment]
This only works correctly on phones, not simulators.  GPS is required for the map control to work.   The default is San Fran.  Parts of this feature will have to be developed using a real phone.
